# Configuration file for bibanl
# VIP journals list - easily maintainable

VIP_JOURNALS <- c(

  # Nature family
  "NATURE",
  "NATURE BIOTECHNOLOGY",
  "NATURE CELL BIOLOGY",
  "NATURE CHEMICAL BIOLOGY",
  "NATURE CLINICAL PRACTICE ONCOLOGY",
  "NATURE COMMUNICATIONS",
  "NATURE GENETICS",
  "NATURE IMMUNOLOGY",
  "NATURE MEDICINE",
  "NATURE METHODS",
  "NATURE NEUROSCIENCE",
  "NATURE PROTOCOLS",
  "NATURE REVIEWS CANCER",
  "NATURE REVIEWS GENETICS",
  "NATURE REVIEWS MICROBIOLOGY",
  "NATURE REVIEWS MOLECULAR CELL BIOLOGY",
  "NATURE STRUCTURAL & MOLECULAR BIOLOGY",
  "NATURE STRUCTURAL BIOLOGY",

  # Other top journals
  "SCIENCE",
  "CELL",
  "NEURON",
  "MOLECULAR CELL",
  "IMMUNITY",
  "PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES OF AMERICA",
  "JOURNAL OF THE AMERICAN CHEMICAL SOCIETY",
  "NEW ENGLAND JOURNAL OF MEDICINE",
  "LANCET",
  "JAMA-JOURNAL OF THE AMERICAN MEDICAL ASSOCIATION"
)

# Default column names for data
DEFAULT_COLS <- list(
  researcher = "researcher",
  total_citations = "tc",
  source = "source",
  pub_year = "pyear"
)
